python_tests(
  name = 'util',
  dependencies = [
    pants('src/python/twitter/thrift/util:thrift_util'),
    pants('src/thrift/com/twitter/thrift/text/testing:testing-py'),
  ],
  sources = globs('*.py'),
)
