java_library(name = 'client',
  dependencies = [
    pants('3rdparty:guava'),
    pants('3rdparty:guice'),
    pants('src/java/com/twitter/common/application'),
    pants('src/java/com/twitter/common/inject'),
    pants('src/java/com/twitter/common/quantity'),
    pants('src/java/com/twitter/common/zookeeper'),
    pants('src/java/com/twitter/common/zookeeper:testing'),
  ],
  sources = globs('*.java'),
)
