#!/usr/bin/env bash
# ==================================================================================================
# Copyright 2011 Twitter, Inc.
# --------------------------------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this work except in compliance with the License.
# You may obtain a copy of the License in the LICENSE file, or at:
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==================================================================================================

source build-support/python/libvirtualenv.sh

PANTS_VERSION=0.0.31

PIP_OPTIONS=(
  ${PIP_OPTIONS}
  --allow-external elementtree
  --allow-unverified elementtree
)

PANTS_PACKAGES=(
  pantsbuild.pants==${PANTS_VERSION}
  pantsbuild.pants.contrib.scrooge==${PANTS_VERSION}
)

setup_virtualenv pants ${PANTS_PACKAGES[@]} ${PIP_OPTIONS[@]}

exec pants "$@"
