#!/usr/bin/env bash
# Wrapper for self-bootstrapping virtualenv
set -e
VIRTUALENV_VERSION=1.11.4

if which python2.7 >/dev/null; then
  PY=`which python2.7`
else
  echo 'No python interpreter found on the path.  Python will not work!' 1>&2
  exit 1
fi

echo "Using $PY" >&2

HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
if ! [ -f "$HERE/virtualenv.dist/BOOTSTRAPPED-$VIRTUALENV_VERSION" ]; then
  pushd "$HERE"
  curl -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-$VIRTUALENV_VERSION.tar.gz
  tar zxvf virtualenv-$VIRTUALENV_VERSION.tar.gz
  # TODO(ksweeney): Checksum
  touch virtualenv-$VIRTUALENV_VERSION/BOOTSTRAPPED-$VIRTUALENV_VERSION  # 2PC
  rm -rf virtualenv.dist
  mv virtualenv-$VIRTUALENV_VERSION virtualenv.dist
  popd
fi

exec "$PY" "$HERE/virtualenv.dist/virtualenv.py" "$@"
