java_tests(name = 'pingpong',
  dependencies = [
    pants('3rdparty:easymock'),
    pants('3rdparty:guava'),
    pants('3rdparty:junit'),
    pants('src/java/com/twitter/common/examples/pingpong'),
    pants('src/java/com/twitter/common/testing'),
  ],
  sources = globs('*.java'),
)
