python_binary(name='dump_meh',
  dependencies=[
               'src/python/mshields/meh:meh',
               'src/python/twitter/common/app',
               ],
  source='dump_meh.py',
)

python_library(name='meh',
  sources=['meh.py'],
)
