java_tests(name = 'http',
  dependencies = [
    '3rdparty/jvm/org/easymock',
    '3rdparty/jvm/org/mortbay/jetty',
    '3rdparty/jvm/junit',
    'src/java/com/twitter/common/quantity',
    'src/java/com/twitter/common/net/http',
    'src/java/com/twitter/common/testing/easymock',
    'src/java/com/twitter/common/util:testing',
  ],
  sources = globs('*.java')
)
