java_tests(name = 'http',
  dependencies = [
    pants('3rdparty:easymock'),
    pants('3rdparty:jetty'),
    pants('3rdparty:junit'),
    pants('src/java/com/twitter/common/quantity'),
    pants('src/java/com/twitter/common/net/http'),
    pants('src/java/com/twitter/common/testing'),
    pants('src/java/com/twitter/common/util:testing'),
  ],
  sources = globs('*.java')
)
