java_tests(name = 'http',
  dependencies = [
    pants('3rdparty/jvm/org/easymock'),
    pants('3rdparty/jvm/org/mortbay/jetty'),
    pants('3rdparty/jvm/junit'),
    pants('src/java/com/twitter/common/quantity'),
    pants('src/java/com/twitter/common/net/http'),
    pants('src/java/com/twitter/common/testing/easymock'),
    pants('src/java/com/twitter/common/util:testing'),
  ],
  sources = globs('*.java')
)
