java_tests(name = 'angrybird',
  dependencies = [
    '3rdparty:guava',
    '3rdparty:hamcrest-core',
    '3rdparty:junit',
    'src/java/com/twitter/common/testing:action',
    'src/java/com/twitter/common/zookeeper/testing/angrybird:angrybird-lib',
    'src/java/com/twitter/common/zookeeper:client',
  ],
  sources = rglobs('*.java'),
)
