java_tests(name = 'angrybird',
  dependencies = [
    '3rdparty/jvm/com/google/guava',
    '3rdparty/jvm/org/hamcrest:hamcrest-core',
    '3rdparty/jvm/junit',
    'src/java/com/twitter/common/testing:action',
    'src/java/com/twitter/common/zookeeper/testing/angrybird:angrybird-lib',
    'src/java/com/twitter/common/zookeeper:client',
  ],
  sources = rglobs('*.java'),
)
