java_library(name = 'flagged',
  dependencies = [
    pants('3rdparty:guava'),
    pants('src/java/com/twitter/common/args'),
    pants('src/java/com/twitter/common/quantity'),
    pants('src/java/com/twitter/common/zookeeper'),
    pants('src/java/com/twitter/common/zookeeper/guice/client'),
  ],
  sources = globs('*.java'),
)
