# ==================================================================================================
# Copyright 2011 Twitter, Inc.
# --------------------------------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this work except in compliance with the License.
# You may obtain a copy of the License in the LICENSE file, or at:
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==================================================================================================

python_test_suite(name = 'all',
  dependencies = [
    'tests/python/twitter/common/app',
    'tests/python/twitter/common/config',
    'tests/python/twitter/common/contextutil',
    'tests/python/twitter/common/decorators',
    'tests/python/twitter/common/dirutil:all',
    'tests/python/twitter/common/exceptions',
    'tests/python/twitter/common/http',
    'tests/python/twitter/common/java',
    'tests/python/twitter/common/jira',
    'tests/python/twitter/common/lang',
    'tests/python/twitter/common/log',
    'tests/python/twitter/common/metrics',
    'tests/python/twitter/common/net:all',
    'tests/python/twitter/common/options',
    'tests/python/twitter/common/quantity',
    'tests/python/twitter/common/recordio:all',
    'tests/python/twitter/common/resourcepool',
    'tests/python/twitter/common/string',
    'tests/python/twitter/common/util',
    'tests/python/twitter/common/zookeeper:all',
  ]
)
