# ==================================================================================================
# Copyright 2011 Twitter, Inc.
# --------------------------------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this work except in compliance with the License.
# You may obtain a copy of the License in the LICENSE file, or at:
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==================================================================================================

python_test_suite(name = 'all',
  dependencies = [
    pants('tests/python/twitter/common/app'),
    pants('tests/python/twitter/common/config'),
    pants('tests/python/twitter/common/contextutil'),
    pants('tests/python/twitter/common/decorators'),
    pants('tests/python/twitter/common/dirutil:all'),
    pants('tests/python/twitter/common/exceptions'),
    pants('tests/python/twitter/common/http'),
    pants('tests/python/twitter/common/java'),
    pants('tests/python/twitter/common/jira'),
    pants('tests/python/twitter/common/lang'),
    pants('tests/python/twitter/common/log'),
    pants('tests/python/twitter/common/metrics'),
    pants('tests/python/twitter/common/net:all'),
    pants('tests/python/twitter/common/options'),
    pants('tests/python/twitter/common/python:all'),
    pants('tests/python/twitter/common/quantity'),
    pants('tests/python/twitter/common/recordio:all'),
    pants('tests/python/twitter/common/resourcepool'),
    pants('tests/python/twitter/common/string'),
    pants('tests/python/twitter/common/util'),
    pants('tests/python/twitter/common/zookeeper:all'),
  ]
)
