java_tests(name = 'concurrent',
  dependencies = [
    '3rdparty/jvm/junit',
    'src/java/com/twitter/common/testing/easymock',
    'src/java/com/twitter/common/util',
  ],
  sources = globs('*Test.java')
)
