java_tests(name = 'concurrent',
  dependencies = [
    pants('3rdparty:junit'),
    pants('src/java/com/twitter/common/testing/easymock'),
    pants('src/java/com/twitter/common/util'),
  ],
  sources = globs('*Test.java')
)
