python_tests(
  name = 'kazoo_client',
  dependencies = [
    'src/python/twitter/common/log',
    'src/python/twitter/common/zookeeper:kazoo_client',
    'src/python/twitter/common/zookeeper:testing',
  ],
  sources = ['kazoo_client_test.py'],
  coverage = 'twitter.common.zookeeper.kazoo_client'
)
