
# It is important to the test that these are separate targets. Do not
# merge them into one.

python_thrift_library(
  name = 'duck-py',
  sources = ['duck.thrift'],
)

python_thrift_library(
  name = 'goose-py',
  sources = ['goose.thrift'],
)
