python_tests(name = 'validators',
  sources = globs('*.py'),
  dependencies = [
    pants('src/python/twitter/common/util'),
    pants('src/python/twitter/pants:pants-deps'),
    pants('src/python/twitter/pants:pants-lib'),
    pants('tests/python/twitter/pants:base-test'),
  ]
)