java_tests(name = 'templating',
  dependencies = [
    pants('3rdparty:guava'),
    pants('3rdparty:junit'),
    pants('3rdparty:stringtemplate'),
    pants('src/java/com/twitter/common/util/templating'),
  ],
  sources = globs('*.java')
)
