java_tests(name = 'filters',
  dependencies = [
    pants('3rdparty:easymock'),
    pants('3rdparty:junit'),
    pants('src/java/com/twitter/common/net/http/filters'),
    pants('src/java/com/twitter/common/testing/easymock'),
    pants('src/java/com/twitter/common/util:testing'),
  ],
  sources = globs('*.java')
)
